// src/routes/+page.svelte
<svelte:head>
	<title>Beth and Josh Club</title>
	<meta name="description" content="Beth and Josh" />
	<meta property="og:image" content="/welcometotheclub.gif" />
	<meta http-equiv="refresh" content="0; url=/home"/>
</svelte:head>

<div style="display: flex;justify-content: center;">
	<img src="/welcometotheclub.gif" width="480" height="270" alt="welcome to the club" />
</div>

// routes/index.tsx
/** @jsx h */
import { h } from "preact";

export default function Home() {
  return (
    <div style="display: flex;justify-content: center;">
      <img
        src="/welcometotheclub.gif"
        width="480" height="270"
        alt="the fresh logo: a sliced lemon dripping with juice"
      />
    </div>
  );
}
